# Build Pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  buildConfiguration: 'Release'

steps:

- task: Npm@1
  displayName: 'NPM Package Restore'
  inputs:
    command: 'ci'
    workingDir: '$(Build.SourcesDirectory)/Vault'

- task: Npm@1
  displayName: 'NPM Build'
  inputs:
    command: 'custom'
    workingDir: '$(Build.SourcesDirectory)/Vault'
    customCommand: 'run build'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: Push Artifact
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'vault-publish-output'
    publishLocation: 'Container'
